[package]
name = "ali"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
serde = "1.0.188"
serde_derive = "1.0.188"
toml = "0.8.0"
